# Generated by Django 5.2.10 on 2026-01-10 06:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('actor_id', models.AutoField(primary_key=True, serialize=False)),
                ('actor_name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'Actor',
            },
        ),
        migrations.CreateModel(
            name='ActorsCast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actor', models.ForeignKey(db_column='actor_id', on_delete=django.db.models.deletion.CASCADE, to='main.actor')),
            ],
            options={
                'db_table': 'Actors Cast',
            },
        ),
        migrations.CreateModel(
            name='CountriesCast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'Countries Cast',
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('country_id', models.AutoField(primary_key=True, serialize=False)),
                ('country_name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'Country',
            },
        ),
        migrations.CreateModel(
            name='Director',
            fields=[
                ('director_id', models.AutoField(primary_key=True, serialize=False)),
                ('director_name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'Director',
            },
        ),
        migrations.CreateModel(
            name='DirectorsCast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('director', models.ForeignKey(db_column='director_id', on_delete=django.db.models.deletion.CASCADE, to='main.director')),
            ],
            options={
                'db_table': 'Directors Cast',
            },
        ),
        migrations.CreateModel(
            name='Show',
            fields=[
                ('show_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=255)),
                ('date_added', models.DateField(blank=True, null=True)),
                ('release_year', models.IntegerField()),
                ('rating', models.CharField(blank=True, max_length=50, null=True)),
                ('duration', models.CharField(blank=True, max_length=50, null=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Shows',
            },
        ),
        migrations.DeleteModel(
            name='Task',
        ),
        migrations.AddField(
            model_name='countriescast',
            name='country',
            field=models.ForeignKey(db_column='country_id', on_delete=django.db.models.deletion.CASCADE, to='main.country'),
        ),
        migrations.AddField(
            model_name='directorscast',
            name='show',
            field=models.ForeignKey(db_column='show_id', on_delete=django.db.models.deletion.CASCADE, to='main.show'),
        ),
        migrations.AddField(
            model_name='countriescast',
            name='show',
            field=models.ForeignKey(db_column='show_id', on_delete=django.db.models.deletion.CASCADE, to='main.show'),
        ),
        migrations.AddField(
            model_name='actorscast',
            name='show',
            field=models.ForeignKey(db_column='show_id', on_delete=django.db.models.deletion.CASCADE, to='main.show'),
        ),
        migrations.AlterUniqueTogether(
            name='directorscast',
            unique_together={('show', 'director')},
        ),
        migrations.AlterUniqueTogether(
            name='countriescast',
            unique_together={('show', 'country')},
        ),
        migrations.AlterUniqueTogether(
            name='actorscast',
            unique_together={('show', 'actor')},
        ),
    ]
